name: Publish

on:
  push:
    branches:
      - test-mac
  workflow_dispatch:

jobs:
  publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    # D:\a\RescueBox-FlaskML-xxx\RescueBox-FlaskML-xxx
    if: ${{ github.repository_owner == 'UMass-Rescue' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Install Node and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - run: npm --version

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install and build
        run: |
          cd ~/RescueBox/RescueBox/RescueBox-Desktop
          echo %cd%
          copy /y ..\build_files\rb.py assets\rb_server
          copy /y ..\build_files\installer.ps1 assets\rb_server
          copy /y ..\build_files\requirements.txt assets\rb_server
          echo "run install"
          npm install
          echo "run postinstall"
          npm run postinstall
          echo "run build"
          npm run build
          echo "run rebuild"
          npm run rebuild
          echo "run exec"
          npm exec electron-builder -- --publish always --mac
          ls release/build
          IF NOT EXIST "release/build/RescueBox-Desktop-2.1.0.dmg" EXIT 1
        shell: sh
