name: Pytest

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ffmpeg and libfuse-for-ufdr
        run: sudo apt-get update && sudo apt-get install -y ffmpeg && sudo apt install fuse

      - name: pull onnx model for deepfake
        run: |
          pip install gdown
          mkdir =p "src/deepfake-detection/deepfake_detection/onnx_models"
          gdown "1tFHTXCGy0hWRFH2H9MP9MpaBJvyHbW0u" --fuzzy -O src/deepfake-detection/deepfake_detection/onnx_models/bnext_M_dffd_model.onnx --continue
          ls -l src/deepfake-detection/deepfake_detection/onnx_models

      - name: pull onnx model for facematch
        run: |
          pip install gdown --force-reinstall
          mkdir -p "src/face-detection-recognition/face_detection_recognition/models"
          gdown "1oDt1i80rUew0UhtY3UiW9EIyd2WfJTZf" --fuzzy -O ./src/face-detection-recognition/face_detection_recognition/models/retinaface-resnet50.onnx --continue
          gdown "1CVCmumM_6C7giGAXJUwHWT--DPFC9bpI" --fuzzy -O ./src/face-detection-recognition/face_detection_recognition/models/facenet512_model.onnx --continue
          
      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          poetry install --with api --with dev

      - name: Run tests
        run: poetry run pytest
